language: python 

python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install: 
    pip install -r req.txt

scripts:
    python tests.py

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - helge.dzierzon@plantandfood.co.nz


